import Link from "next/link";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { AuditAction, AuditEntityType } from "@prisma/client";
import { TasksBoard } from "@/components/tasks-board";
import { requireUser } from "@/lib/auth";
import { writeAuditLog } from "@/lib/audit";
import { prisma } from "@/lib/prisma";
import { hasPermission } from "@/lib/rbac";
import { taskCreateSchema } from "@/lib/validators";

export default async function TasksPage({
  searchParams
}: {
  searchParams: { new?: string };
}) {
  const user = await requireUser();

  const [tasks, dossiers] = await Promise.all([
    prisma.task.findMany({
      where: { dossier: { deletedAt: null } },
      include: { dossier: true },
      orderBy: [{ status: "asc" }, { deadline: "asc" }, { createdAt: "desc" }]
    }),
    prisma.dossier.findMany({ where: { deletedAt: null }, orderBy: { title: "asc" } })
  ]);

  async function createTaskAction(formData: FormData) {
    "use server";

    const currentUser = await requireUser();
    if (!hasPermission(currentUser.role, "TASK", "CREATE")) {
      throw new Error("FORBIDDEN");
    }

    const deadlineRaw = String(formData.get("deadline") || "");

    const parsed = taskCreateSchema.safeParse({
      dossierId: formData.get("dossierId"),
      title: formData.get("title"),
      description: formData.get("description"),
      deadline: deadlineRaw ? new Date(deadlineRaw).toISOString() : null,
      priority: formData.get("priority") || "MEDIUM",
      status: formData.get("status") || "TODO",
      autoGenerated: false
    });

    if (!parsed.success) {
      throw new Error("Invalid task data");
    }

    const created = await prisma.task.create({
      data: {
        dossierId: parsed.data.dossierId,
        title: parsed.data.title,
        description: parsed.data.description || null,
        deadline: parsed.data.deadline ? new Date(parsed.data.deadline) : null,
        priority: parsed.data.priority,
        status: parsed.data.status,
        autoGenerated: false
      }
    });

    await writeAuditLog({
      actorUserId: currentUser.id,
      entityType: AuditEntityType.TASK,
      entityId: created.id,
      action: AuditAction.CREATE,
      after: created
    });

    revalidatePath("/tasks");
    revalidatePath("/dashboard");
    redirect("/tasks");
  }

  const canCreate = hasPermission(user.role, "TASK", "CREATE");
  const canDelete = hasPermission(user.role, "TASK", "DELETE");
  const openTasksCount = tasks.filter((task) => task.status !== "DONE").length;
  const boardTasks = tasks.map((task) => ({
    id: task.id,
    title: task.title,
    priority: task.priority,
    dossierId: task.dossierId,
    dossierTitle: task.dossier.title,
    deadline: task.deadline ? task.deadline.toISOString() : null,
    status: task.status
  }));

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="text-4xl font-extrabold tracking-tight text-slate-800">Taken</h1>
          <p className="mt-1 text-base text-slate-500">{openTasksCount} openstaande taken</p>
        </div>
        {canCreate ? <Link href="/tasks?new=1" className="ld-btn-primary">+ Nieuwe taak</Link> : null}
      </div>

      <TasksBoard initialTasks={boardTasks} canDelete={canDelete} />

      {searchParams.new === "1" && canCreate ? (
        <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-slate-900/45 p-6">
          <div className="w-full max-w-3xl rounded-3xl bg-white p-8 shadow-2xl">
            <h2 className="text-2xl font-extrabold text-slate-800">Nieuwe taak</h2>
            <form action={createTaskAction} className="mt-6 space-y-4">
              <div>
                <label className="mb-2 block text-sm font-semibold text-slate-700">Dossier *</label>
                <select name="dossierId" required className="ld-input">
                  <option value="">Selecteer dossier...</option>
                  {dossiers.map((dossier) => (
                    <option key={dossier.id} value={dossier.id}>
                      {dossier.title}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="mb-2 block text-sm font-semibold text-slate-700">Titel *</label>
                <input name="title" required className="ld-input" />
              </div>

              <div className="grid gap-4 md:grid-cols-2">
                <div>
                  <label className="mb-2 block text-sm font-semibold text-slate-700">Deadline</label>
                  <input name="deadline" type="datetime-local" className="ld-input" />
                </div>
                <div>
                  <label className="mb-2 block text-sm font-semibold text-slate-700">Prioriteit</label>
                  <select name="priority" defaultValue="MEDIUM" className="ld-input">
                    <option value="LOW">Normaal</option>
                    <option value="MEDIUM">Hoog</option>
                    <option value="HIGH">Urgent</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="mb-2 block text-sm font-semibold text-slate-700">Beschrijving</label>
                <textarea name="description" rows={4} className="ld-input" />
              </div>

              <input type="hidden" name="status" value="TODO" />

              <div className="flex justify-end gap-3 pt-2">
                <Link href="/tasks" className="ld-btn-secondary">Annuleren</Link>
                <button type="submit" className="ld-btn-primary">Toevoegen</button>
              </div>
            </form>
          </div>
        </div>
      ) : null}
    </div>
  );
}
