"use client";

import { useMemo, useState } from "react";
import type { AIOutput } from "@/lib/validators";

type AgentAction = "SUMMARY" | "SUGGEST_TASKS" | "REVIEW_LATEST_DOC" | "DEADLINE_SCAN";

type AIResponse = {
  aiEvent: { id: string; confidence: number; trigger: string; createdAt: string };
  output: AIOutput;
};

const disclaimer =
  "AI output is a suggestion only. It may be incomplete. Do not treat it as legal advice or automatic decisions.";

export function DossierAIPanel({
  dossierId,
  latestDocumentId
}: {
  dossierId: string;
  latestDocumentId?: string;
}) {
  const [loading, setLoading] = useState<AgentAction | null>(null);
  const [applying, setApplying] = useState<"summary" | "tasks" | null>(null);
  const [response, setResponse] = useState<AIResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function runAgent(action: AgentAction) {
    setLoading(action);
    setError(null);

    try {
      const res = await fetch("/api/ai/agent", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          dossierId,
          action,
          documentId: action === "REVIEW_LATEST_DOC" ? latestDocumentId : undefined
        })
      });

      if (!res.ok) {
        const data = (await res.json()) as { error?: string };
        throw new Error(data.error ?? "AI request failed");
      }

      const data = (await res.json()) as AIResponse;
      setResponse(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "AI request failed");
    } finally {
      setLoading(null);
    }
  }

  async function applySummary() {
    if (!response) {
      return;
    }

    setApplying("summary");
    setError(null);

    try {
      const res = await fetch(`/api/dossiers/${dossierId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ summary: response.output.summary })
      });

      if (!res.ok) {
        const data = (await res.json()) as { error?: string };
        throw new Error(data.error ?? "Failed to apply summary");
      }

      window.location.reload();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to apply summary");
    } finally {
      setApplying(null);
    }
  }

  async function applyTasks() {
    if (!response || response.output.proposedTasks.length === 0) {
      return;
    }

    setApplying("tasks");
    setError(null);

    try {
      for (const task of response.output.proposedTasks) {
        const res = await fetch("/api/tasks", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            dossierId,
            title: task.title,
            description: `${task.rationale}\n\nSources: ${task.sourceRefs.join(", ")}`,
            deadline: task.deadline,
            priority: task.priority,
            status: "TODO",
            autoGenerated: true
          })
        });

        if (!res.ok) {
          const data = (await res.json()) as { error?: string };
          throw new Error(data.error ?? "Failed to apply tasks");
        }
      }

      window.location.reload();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to apply tasks");
    } finally {
      setApplying(null);
    }
  }

  const confidenceText = useMemo(() => {
    if (!response) {
      return "-";
    }

    return `${Math.round(response.output.confidence * 100)}%`;
  }, [response]);

  return (
    <div className="rounded border border-slate-200 bg-white p-4">
      <div className="flex items-center justify-between">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-600">AI Assistant</h2>
      </div>
      <p className="mt-2 text-xs text-slate-500">{disclaimer}</p>

      <div className="mt-4 grid gap-2 sm:grid-cols-2">
        <button
          onClick={() => runAgent("SUMMARY")}
          disabled={loading !== null}
          className="rounded border border-slate-300 px-3 py-2 text-sm hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-60"
        >
          {loading === "SUMMARY" ? "Generating..." : "Generate dossier summary"}
        </button>
        <button
          onClick={() => runAgent("SUGGEST_TASKS")}
          disabled={loading !== null}
          className="rounded border border-slate-300 px-3 py-2 text-sm hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-60"
        >
          {loading === "SUGGEST_TASKS" ? "Generating..." : "Suggest next tasks"}
        </button>
        <button
          onClick={() => runAgent("REVIEW_LATEST_DOC")}
          disabled={loading !== null || !latestDocumentId}
          className="rounded border border-slate-300 px-3 py-2 text-sm hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-60"
        >
          {loading === "REVIEW_LATEST_DOC" ? "Reviewing..." : "Review latest document"}
        </button>
        <button
          onClick={() => runAgent("DEADLINE_SCAN")}
          disabled={loading !== null}
          className="rounded border border-slate-300 px-3 py-2 text-sm hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-60"
        >
          {loading === "DEADLINE_SCAN" ? "Scanning..." : "Run deadline risk scan"}
        </button>
      </div>

      {error ? <p className="mt-4 rounded bg-red-50 p-2 text-xs text-red-700">{error}</p> : null}

      {response ? (
        <div className="mt-4 space-y-4 rounded border border-blue-100 bg-blue-50 p-3">
          <div className="flex items-center justify-between">
            <p className="text-sm font-medium">AI suggestion output</p>
            <p className="text-xs text-slate-600">Confidence: {confidenceText}</p>
          </div>

          <div>
            <p className="text-xs font-semibold uppercase text-slate-600">Summary suggestion</p>
            <p className="mt-1 text-sm text-slate-800">{response.output.summary}</p>
          </div>

          <div>
            <p className="text-xs font-semibold uppercase text-slate-600">Risks</p>
            <ul className="mt-1 space-y-2">
              {response.output.risks.map((risk, index) => (
                <li key={`${risk.title}-${index}`} className="rounded border border-blue-200 bg-white p-2 text-sm">
                  <p className="font-medium">
                    {risk.title} ({risk.severity})
                  </p>
                  <p className="text-slate-700">{risk.detail}</p>
                  <p className="text-xs text-slate-500">Sources: {risk.sourceRefs.join(", ") || "-"}</p>
                </li>
              ))}
            </ul>
          </div>

          <div>
            <p className="text-xs font-semibold uppercase text-slate-600">Proposed tasks</p>
            <ul className="mt-1 space-y-2">
              {response.output.proposedTasks.map((task, index) => (
                <li key={`${task.title}-${index}`} className="rounded border border-blue-200 bg-white p-2 text-sm">
                  <p className="font-medium">{task.title}</p>
                  <p className="text-slate-700">{task.rationale}</p>
                  <p className="text-xs text-slate-500">Sources: {task.sourceRefs.join(", ") || "-"}</p>
                </li>
              ))}
            </ul>
          </div>

          <div className="flex flex-wrap gap-2">
            <button
              onClick={applySummary}
              disabled={applying !== null}
              className="rounded bg-primary-600 px-3 py-2 text-sm font-medium text-white hover:bg-primary-700 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {applying === "summary" ? "Applying..." : "Apply summary"}
            </button>
            <button
              onClick={applyTasks}
              disabled={applying !== null || response.output.proposedTasks.length === 0}
              className="rounded border border-primary-600 px-3 py-2 text-sm font-medium text-primary-700 hover:bg-primary-50 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {applying === "tasks" ? "Applying..." : "Create proposed tasks"}
            </button>
          </div>
        </div>
      ) : null}
    </div>
  );
}
