import { z } from "zod";

const optionalString = z.string().trim().min(1).optional().or(z.literal(""));

export const loginSchema = z.object({
  email: z.string().email(),
  password: z.string().min(4)
});

export const clientCreateSchema = z.object({
  type: z.enum(["PERSON", "COMPANY"]),
  name: z.string().min(1),
  email: z.string().email().optional().or(z.literal("")),
  phone: optionalString,
  address: optionalString
});

export const clientUpdateSchema = clientCreateSchema.partial().refine(
  (value) => Object.keys(value).length > 0,
  "At least one field is required"
);

export const dossierCreateSchema = z.object({
  clientId: z.string().min(1),
  title: z.string().min(1),
  type: z.enum(["CONTRACT", "DISPUTE", "REAL_ESTATE", "OTHER"]),
  status: z.enum(["OPEN", "ON_HOLD", "CLOSED"]).optional(),
  ownerUserId: z.string().min(1),
  summary: optionalString,
  aiContext: optionalString
});

export const dossierUpdateSchema = dossierCreateSchema
  .partial()
  .refine((value) => Object.keys(value).length > 0, "At least one field is required");

export const taskCreateSchema = z.object({
  dossierId: z.string().min(1),
  title: z.string().min(1),
  description: optionalString,
  deadline: z.string().datetime().nullable().optional(),
  priority: z.enum(["LOW", "MEDIUM", "HIGH"]).optional(),
  status: z.enum(["TODO", "IN_PROGRESS", "DONE"]).optional(),
  autoGenerated: z.boolean().optional()
});

export const taskUpdateSchema = taskCreateSchema
  .omit({ dossierId: true })
  .partial()
  .refine((value) => Object.keys(value).length > 0, "At least one field is required");

export const timeEntryCreateSchema = z.object({
  dossierId: z.string().min(1),
  startAt: z.string().datetime(),
  endAt: z.string().datetime().nullable().optional(),
  description: z.string().min(1),
  autoCaptured: z.boolean().optional()
});

export const timeEntryUpdateSchema = z
  .object({
    endAt: z.string().datetime().nullable().optional(),
    description: z.string().min(1).optional(),
    autoCaptured: z.boolean().optional()
  })
  .refine((value) => Object.keys(value).length > 0, "At least one field is required");

export const documentCreateSchema = z.object({
  dossierId: z.string().min(1),
  type: z.enum(["LETTER", "CONTRACT", "NOTE", "OTHER"]),
  title: z.string().min(1),
  content: z.string().optional().default(""),
  source: z.enum(["TEMPLATE", "UPLOAD", "AI"]).optional(),
  version: z.number().int().min(1).optional(),
  templateId: z.string().optional().nullable(),
  useTemplate: z.boolean().optional()
});

export const documentUpdateSchema = z
  .object({
    type: z.enum(["LETTER", "CONTRACT", "NOTE", "OTHER"]).optional(),
    title: z.string().min(1).optional(),
    content: z.string().min(1).optional(),
    source: z.enum(["TEMPLATE", "UPLOAD", "AI"]).optional(),
    version: z.number().int().min(1).optional()
  })
  .refine((value) => Object.keys(value).length > 0, "At least one field is required");

export const templateCreateSchema = z.object({
  name: z.string().min(1),
  type: z.string().min(1),
  body: z.string().min(1)
});

export const templateUpdateSchema = templateCreateSchema
  .partial()
  .refine((value) => Object.keys(value).length > 0, "At least one field is required");

export const aiAgentRequestSchema = z.object({
  dossierId: z.string().min(1),
  action: z.enum(["SUMMARY", "SUGGEST_TASKS", "REVIEW_LATEST_DOC", "DEADLINE_SCAN"]),
  documentId: z.string().optional()
});

export const aiOutputSchema = z.object({
  summary: z.string(),
  suggestions: z.array(
    z.object({
      type: z.enum(["TASK", "DOC", "RISK"]),
      title: z.string(),
      detail: z.string(),
      sourceRefs: z.array(z.string())
    })
  ),
  risks: z.array(
    z.object({
      title: z.string(),
      detail: z.string(),
      severity: z.enum(["LOW", "MEDIUM", "HIGH"]),
      sourceRefs: z.array(z.string())
    })
  ),
  proposedTasks: z.array(
    z.object({
      title: z.string(),
      deadline: z.string().datetime().nullable(),
      priority: z.enum(["LOW", "MEDIUM", "HIGH"]),
      rationale: z.string(),
      sourceRefs: z.array(z.string())
    })
  ),
  confidence: z.number().min(0).max(1)
});

export type AIOutput = z.infer<typeof aiOutputSchema>;
