import type { LLMClient } from "@/lib/ai/llm";

export class MockLLMClient implements LLMClient {
  async generate(_system: string, user: string): Promise<string> {
    const hasDeadline = user.toLowerCase().includes("deadline");
    const now = new Date().toISOString();

    return JSON.stringify({
      summary: hasDeadline
        ? "Two high-priority deadlines are approaching; prioritize liability and filing prep."
        : "Dossier is active with open legal drafting tasks and pending document review.",
      suggestions: [
        {
          type: "TASK",
          title: "Validate liability cap fallback language",
          detail: "Compare fallback position against latest draft and client risk appetite.",
          sourceRefs: ["document:latest", "task:open"]
        },
        {
          type: "RISK",
          title: "Missed filing risk",
          detail: "At least one task is due within 72 hours and still not done.",
          sourceRefs: ["task:deadline"]
        }
      ],
      risks: [
        {
          title: "Deadline proximity",
          detail: "A critical task deadline is near and status is not DONE.",
          severity: hasDeadline ? "HIGH" : "MEDIUM",
          sourceRefs: ["task:deadline"]
        }
      ],
      proposedTasks: [
        {
          title: "Call client for go/no-go on indemnity position",
          deadline: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
          priority: "HIGH",
          rationale: "Needed before next negotiation round.",
          sourceRefs: ["document:latest"]
        },
        {
          title: "Prepare redline response memo",
          deadline: null,
          priority: "MEDIUM",
          rationale: `Generated by deterministic mock at ${now}.`,
          sourceRefs: ["document:latest", "task:open"]
        }
      ],
      confidence: 0.73
    });
  }
}
