import { notFound } from "next/navigation";
import { revalidatePath } from "next/cache";
import { AuditAction, AuditEntityType, DocumentSource, DocumentType, TaskPriority } from "@prisma/client";
import { DossierAIPanel } from "@/components/dossier-ai-panel";
import { requireUser } from "@/lib/auth";
import { writeAuditLog } from "@/lib/audit";
import { prisma } from "@/lib/prisma";
import { hasPermission } from "@/lib/rbac";
import { renderTemplate } from "@/lib/templates";
import {
  dossierUpdateSchema,
  documentCreateSchema,
  taskCreateSchema,
  timeEntryCreateSchema
} from "@/lib/validators";

export default async function DossierDetailPage({ params }: { params: { id: string } }) {
  const user = await requireUser();

  const [dossier, templates, owners] = await Promise.all([
    prisma.dossier.findFirst({
      where: { id: params.id, deletedAt: null },
      include: {
        client: true,
        owner: true,
        tasks: { orderBy: [{ deadline: "asc" }, { createdAt: "desc" }] },
        documents: { orderBy: { createdAt: "desc" } },
        timeEntries: {
          include: { user: true },
          orderBy: { createdAt: "desc" }
        }
      }
    }),
    prisma.template.findMany({ orderBy: { name: "asc" } }),
    prisma.user.findMany({ orderBy: { name: "asc" } })
  ]);

  if (!dossier) {
    notFound();
  }

  async function updateDossierAction(formData: FormData) {
    "use server";

    const currentUser = await requireUser();
    if (!hasPermission(currentUser.role, "DOSSIER", "UPDATE")) {
      throw new Error("FORBIDDEN");
    }

    const parsed = dossierUpdateSchema.safeParse({
      title: formData.get("title"),
      type: formData.get("type"),
      status: formData.get("status"),
      ownerUserId: formData.get("ownerUserId"),
      summary: formData.get("summary"),
      aiContext: formData.get("aiContext")
    });

    if (!parsed.success) {
      throw new Error("Invalid dossier update");
    }

    const before = await prisma.dossier.findUnique({ where: { id: params.id } });
    if (!before) {
      throw new Error("Dossier not found");
    }

    const updated = await prisma.dossier.update({
      where: { id: params.id },
      data: {
        ...parsed.data,
        summary: parsed.data.summary || null,
        aiContext: parsed.data.aiContext || null
      }
    });

    await writeAuditLog({
      actorUserId: currentUser.id,
      entityType: AuditEntityType.DOSSIER,
      entityId: updated.id,
      action: AuditAction.UPDATE,
      before,
      after: updated
    });

    revalidatePath(`/dossiers/${params.id}`);
    revalidatePath("/dossiers");
  }

  async function archiveDossierAction() {
    "use server";

    const currentUser = await requireUser();
    if (!hasPermission(currentUser.role, "DOSSIER", "DELETE")) {
      throw new Error("FORBIDDEN");
    }

    const before = await prisma.dossier.findUnique({ where: { id: params.id } });
    if (!before) {
      return;
    }

    const updated = await prisma.dossier.update({
      where: { id: params.id },
      data: { deletedAt: new Date() }
    });

    await writeAuditLog({
      actorUserId: currentUser.id,
      entityType: AuditEntityType.DOSSIER,
      entityId: params.id,
      action: AuditAction.DELETE,
      before,
      after: updated
    });

    revalidatePath("/dossiers");
  }

  async function createTaskAction(formData: FormData) {
    "use server";

    const currentUser = await requireUser();
    if (!hasPermission(currentUser.role, "TASK", "CREATE")) {
      throw new Error("FORBIDDEN");
    }

    const deadlineRaw = String(formData.get("deadline") || "");

    const parsed = taskCreateSchema.safeParse({
      dossierId: params.id,
      title: formData.get("title"),
      description: formData.get("description"),
      deadline: deadlineRaw ? new Date(deadlineRaw).toISOString() : null,
      priority: formData.get("priority") || TaskPriority.MEDIUM,
      status: formData.get("status") || "TODO",
      autoGenerated: false
    });

    if (!parsed.success) {
      throw new Error("Invalid task data");
    }

    const created = await prisma.task.create({
      data: {
        dossierId: params.id,
        title: parsed.data.title,
        description: parsed.data.description || null,
        deadline: parsed.data.deadline ? new Date(parsed.data.deadline) : null,
        priority: parsed.data.priority,
        status: parsed.data.status,
        autoGenerated: false
      }
    });

    await writeAuditLog({
      actorUserId: currentUser.id,
      entityType: AuditEntityType.TASK,
      entityId: created.id,
      action: AuditAction.CREATE,
      after: created
    });

    revalidatePath(`/dossiers/${params.id}`);
    revalidatePath("/tasks");
    revalidatePath("/dashboard");
  }

  async function createDocumentAction(formData: FormData) {
    "use server";

    const currentUser = await requireUser();
    if (!hasPermission(currentUser.role, "DOCUMENT", "CREATE")) {
      throw new Error("FORBIDDEN");
    }

    const templateId = String(formData.get("templateId") || "");
    const bodyRaw = String(formData.get("content") || "");

    const parsed = documentCreateSchema.safeParse({
      dossierId: params.id,
      type: formData.get("type") || DocumentType.NOTE,
      title: formData.get("title"),
      content: bodyRaw || "temp",
      source: formData.get("source") || DocumentSource.UPLOAD,
      version: Number(formData.get("version") || 1),
      templateId: templateId || null,
      useTemplate: Boolean(templateId)
    });

    if (!parsed.success) {
      throw new Error("Invalid document data");
    }

    let content = bodyRaw;
    if (templateId) {
      const [template, dossierForTemplate] = await Promise.all([
        prisma.template.findUnique({ where: { id: templateId } }),
        prisma.dossier.findUnique({ where: { id: params.id }, include: { client: true } })
      ]);

      if (!dossierForTemplate) {
        throw new Error("Dossier not found");
      }

      if (template) {
        content = renderTemplate(template.body, {
          "client.name": dossierForTemplate.client.name,
          "dossier.title": dossierForTemplate.title,
          "user.name": currentUser.name
        });
      }
    }

    if (!content.trim()) {
      throw new Error("Document content cannot be empty");
    }

    const created = await prisma.document.create({
      data: {
        dossierId: params.id,
        type: parsed.data.type,
        title: parsed.data.title,
        content,
        source: templateId ? DocumentSource.TEMPLATE : parsed.data.source,
        version: parsed.data.version ?? 1
      }
    });

    await writeAuditLog({
      actorUserId: currentUser.id,
      entityType: AuditEntityType.DOCUMENT,
      entityId: created.id,
      action: AuditAction.CREATE,
      after: created
    });

    revalidatePath(`/dossiers/${params.id}`);
    revalidatePath("/documents");
    revalidatePath("/dashboard");
  }

  async function createTimeEntryAction(formData: FormData) {
    "use server";

    const currentUser = await requireUser();
    if (!hasPermission(currentUser.role, "TIME_ENTRY", "CREATE")) {
      throw new Error("FORBIDDEN");
    }

    const startAt = String(formData.get("startAt") || "");
    const endAt = String(formData.get("endAt") || "");

    const parsed = timeEntryCreateSchema.safeParse({
      dossierId: params.id,
      description: formData.get("description"),
      startAt: new Date(startAt).toISOString(),
      endAt: endAt ? new Date(endAt).toISOString() : null,
      autoCaptured: false
    });

    if (!parsed.success) {
      throw new Error("Invalid time entry data");
    }

    const created = await prisma.timeEntry.create({
      data: {
        dossierId: params.id,
        userId: currentUser.id,
        description: parsed.data.description,
        startAt: new Date(parsed.data.startAt),
        endAt: parsed.data.endAt ? new Date(parsed.data.endAt) : null,
        autoCaptured: false
      }
    });

    await writeAuditLog({
      actorUserId: currentUser.id,
      entityType: AuditEntityType.TIME_ENTRY,
      entityId: created.id,
      action: AuditAction.CREATE,
      after: created
    });

    revalidatePath(`/dossiers/${params.id}`);
    revalidatePath("/time-tracking");
  }

  const canUpdateDossier = hasPermission(user.role, "DOSSIER", "UPDATE");
  const canDeleteDossier = hasPermission(user.role, "DOSSIER", "DELETE");

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-xl font-semibold">{dossier.title}</h1>
        {canDeleteDossier ? (
          <form action={archiveDossierAction}>
            <button className="rounded border border-red-300 px-3 py-1.5 text-sm text-red-700 hover:bg-red-50" type="submit">
              Archive dossier
            </button>
          </form>
        ) : null}
      </div>

      <section className="grid gap-6 lg:grid-cols-3">
        <div className="space-y-4 lg:col-span-2">
          {canUpdateDossier ? (
            <form action={updateDossierAction} className="grid gap-3 rounded border border-slate-200 bg-white p-4 md:grid-cols-2">
              <div>
                <label className="mb-1 block text-sm">Title</label>
                <input name="title" defaultValue={dossier.title} className="w-full rounded border border-slate-300 px-2 py-2 text-sm" />
              </div>
              <div>
                <label className="mb-1 block text-sm">Owner</label>
                <select name="ownerUserId" defaultValue={dossier.ownerUserId} className="w-full rounded border border-slate-300 px-2 py-2 text-sm">
                  {owners.map((owner) => (
                    <option key={owner.id} value={owner.id}>
                      {owner.name}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className="mb-1 block text-sm">Type</label>
                <select name="type" defaultValue={dossier.type} className="w-full rounded border border-slate-300 px-2 py-2 text-sm">
                  <option value="CONTRACT">Contract</option>
                  <option value="DISPUTE">Dispute</option>
                  <option value="REAL_ESTATE">Real estate</option>
                  <option value="OTHER">Other</option>
                </select>
              </div>
              <div>
                <label className="mb-1 block text-sm">Status</label>
                <select name="status" defaultValue={dossier.status} className="w-full rounded border border-slate-300 px-2 py-2 text-sm">
                  <option value="OPEN">Open</option>
                  <option value="ON_HOLD">On hold</option>
                  <option value="CLOSED">Closed</option>
                </select>
              </div>
              <div className="md:col-span-2">
                <label className="mb-1 block text-sm">Summary</label>
                <textarea name="summary" rows={3} defaultValue={dossier.summary ?? ""} className="w-full rounded border border-slate-300 px-2 py-2 text-sm" />
              </div>
              <div className="md:col-span-2">
                <label className="mb-1 block text-sm">AI context</label>
                <textarea name="aiContext" rows={2} defaultValue={dossier.aiContext ?? ""} className="w-full rounded border border-slate-300 px-2 py-2 text-sm" />
              </div>
              <div className="md:col-span-2">
                <button className="rounded bg-primary-600 px-4 py-2 text-sm font-medium text-white hover:bg-primary-700" type="submit">
                  Save dossier
                </button>
              </div>
            </form>
          ) : null}

          <section className="rounded border border-slate-200 bg-white p-4">
            <h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-slate-600">Tasks</h2>
            {hasPermission(user.role, "TASK", "CREATE") ? (
              <form action={createTaskAction} className="mb-4 grid gap-3 md:grid-cols-4">
                <input name="title" placeholder="Task title" required className="rounded border border-slate-300 px-2 py-2 text-sm md:col-span-2" />
                <input name="deadline" type="datetime-local" className="rounded border border-slate-300 px-2 py-2 text-sm" />
                <select name="priority" defaultValue="MEDIUM" className="rounded border border-slate-300 px-2 py-2 text-sm">
                  <option value="LOW">Low</option>
                  <option value="MEDIUM">Medium</option>
                  <option value="HIGH">High</option>
                </select>
                <textarea name="description" placeholder="Description" className="rounded border border-slate-300 px-2 py-2 text-sm md:col-span-4" />
                <button type="submit" className="rounded bg-slate-900 px-3 py-2 text-sm font-medium text-white md:col-span-1">
                  Add task
                </button>
              </form>
            ) : null}
            <ul className="space-y-2">
              {dossier.tasks.length === 0 ? (
                <li className="text-sm text-slate-500">No tasks yet.</li>
              ) : (
                dossier.tasks.map((task) => (
                  <li key={task.id} className="rounded border border-slate-100 p-3 text-sm">
                    <p className="font-medium">{task.title}</p>
                    <p className="text-xs text-slate-500">
                      {task.status} · {task.priority}
                      {task.deadline ? ` · due ${new Date(task.deadline).toLocaleString()}` : ""}
                    </p>
                  </li>
                ))
              )}
            </ul>
          </section>

          <section className="rounded border border-slate-200 bg-white p-4">
            <h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-slate-600">Documents</h2>
            {hasPermission(user.role, "DOCUMENT", "CREATE") ? (
              <form action={createDocumentAction} className="mb-4 grid gap-3 md:grid-cols-2">
                <input name="title" placeholder="Document title" required className="rounded border border-slate-300 px-2 py-2 text-sm" />
                <select name="type" defaultValue="NOTE" className="rounded border border-slate-300 px-2 py-2 text-sm">
                  <option value="LETTER">Letter</option>
                  <option value="CONTRACT">Contract</option>
                  <option value="NOTE">Note</option>
                  <option value="OTHER">Other</option>
                </select>
                <select name="templateId" className="rounded border border-slate-300 px-2 py-2 text-sm">
                  <option value="">No template</option>
                  {templates.map((template) => (
                    <option key={template.id} value={template.id}>
                      {template.name}
                    </option>
                  ))}
                </select>
                <select name="source" defaultValue="UPLOAD" className="rounded border border-slate-300 px-2 py-2 text-sm">
                  <option value="UPLOAD">Upload</option>
                  <option value="TEMPLATE">Template</option>
                  <option value="AI">AI</option>
                </select>
                <textarea
                  name="content"
                  placeholder="Content (optional if template selected)"
                  className="rounded border border-slate-300 px-2 py-2 text-sm md:col-span-2"
                  rows={4}
                />
                <button type="submit" className="rounded bg-slate-900 px-3 py-2 text-sm font-medium text-white md:col-span-1">
                  Add document
                </button>
              </form>
            ) : null}
            <ul className="space-y-2">
              {dossier.documents.length === 0 ? (
                <li className="text-sm text-slate-500">No documents yet.</li>
              ) : (
                dossier.documents.map((document) => (
                  <li key={document.id} className="rounded border border-slate-100 p-3 text-sm">
                    <p className="font-medium">{document.title}</p>
                    <p className="text-xs text-slate-500">
                      {document.type} · v{document.version} · {document.source}
                    </p>
                  </li>
                ))
              )}
            </ul>
          </section>

          <section className="rounded border border-slate-200 bg-white p-4">
            <h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-slate-600">Time Entries</h2>
            {hasPermission(user.role, "TIME_ENTRY", "CREATE") ? (
              <form action={createTimeEntryAction} className="mb-4 grid gap-3 md:grid-cols-3">
                <input name="startAt" type="datetime-local" required className="rounded border border-slate-300 px-2 py-2 text-sm" />
                <input name="endAt" type="datetime-local" className="rounded border border-slate-300 px-2 py-2 text-sm" />
                <input name="description" required placeholder="What did you do?" className="rounded border border-slate-300 px-2 py-2 text-sm" />
                <button type="submit" className="rounded bg-slate-900 px-3 py-2 text-sm font-medium text-white md:col-span-1">
                  Add time
                </button>
              </form>
            ) : null}
            <ul className="space-y-2">
              {dossier.timeEntries.length === 0 ? (
                <li className="text-sm text-slate-500">No time entries yet.</li>
              ) : (
                dossier.timeEntries.map((entry) => (
                  <li key={entry.id} className="rounded border border-slate-100 p-3 text-sm">
                    <p className="font-medium">{entry.description}</p>
                    <p className="text-xs text-slate-500">
                      {entry.user.name} · {new Date(entry.startAt).toLocaleString()} -{" "}
                      {entry.endAt ? new Date(entry.endAt).toLocaleString() : "Running"}
                    </p>
                  </li>
                ))
              )}
            </ul>
          </section>
        </div>

        <div>
          <DossierAIPanel dossierId={dossier.id} latestDocumentId={dossier.documents[0]?.id} />
        </div>
      </section>
    </div>
  );
}
