import { AuditAction, AuditEntityType } from "@prisma/client";
import { jsonError, parseBody, requireApiUser } from "@/lib/api";
import { writeAuditLog } from "@/lib/audit";
import { prisma } from "@/lib/prisma";
import { hasPermission } from "@/lib/rbac";
import { taskCreateSchema } from "@/lib/validators";

export async function GET(request: Request) {
  const auth = await requireApiUser();
  if (auth.error) {
    return auth.error;
  }

  if (!hasPermission(auth.user.role, "TASK", "READ")) {
    return jsonError("Forbidden", 403);
  }

  const url = new URL(request.url);
  const dossierId = url.searchParams.get("dossierId");

  const tasks = await prisma.task.findMany({
    where: {
      dossierId: dossierId ?? undefined,
      dossier: { deletedAt: null }
    },
    orderBy: [{ deadline: "asc" }, { createdAt: "desc" }]
  });

  return Response.json(tasks);
}

export async function POST(request: Request) {
  const auth = await requireApiUser();
  if (auth.error) {
    return auth.error;
  }

  if (!hasPermission(auth.user.role, "TASK", "CREATE")) {
    return jsonError("Forbidden", 403);
  }

  const parsed = await parseBody(request, taskCreateSchema);
  if (parsed.error) {
    return parsed.error;
  }

  const created = await prisma.task.create({
    data: {
      dossierId: parsed.data.dossierId,
      title: parsed.data.title,
      description: parsed.data.description || null,
      deadline: parsed.data.deadline ? new Date(parsed.data.deadline) : null,
      priority: parsed.data.priority,
      status: parsed.data.status,
      autoGenerated: parsed.data.autoGenerated ?? false
    }
  });

  await writeAuditLog({
    actorUserId: auth.user.id,
    entityType: AuditEntityType.TASK,
    entityId: created.id,
    action: AuditAction.CREATE,
    after: created
  });

  return Response.json(created, { status: 201 });
}
